### ISSUE TITLE
repo migration from hprc to GA

### ISSUE THREAD

**Issue by DininduSenanayake** [GenomicsAotearoa/long-read-assembly#17]
FROM [hprc repo](https://github.com/human-pangenomics/hprc-tutorials/tree/GA-workshop/assembly/genomics_aotearoa) TO [GA repo](https://github.com/GenomicsAotearoa/long-read-assembly)

**Comment by JSBoey** [comment]
There are parts of the [hprc repo](https://github.com/human-pangenomics/hprc-tutorials/blob/GA-workshop/assembly/genomics_aotearoa/pages/day3a_assembly_qc.md) that contains `srun` directly from the Jupyter terminal. It might be good to modify these and wrap all into an `sbatch` script.

**Comment by DininduSenanayake** [comment]
This is all done @JSBoey
