### ISSUE TITLE
Merqury running on trio requires additional R packages

### ISSUE THREAD

**Issue by JSBoey** [GenomicsAotearoa/long-read-assembly#18]
This is referring to the script that spawns `merqury2` in this [section](https://github.com/human-pangenomics/hprc-tutorials/blob/GA-workshop/assembly/genomics_aotearoa/pages/day3a_assembly_qc.md#correctness-qv-using-merqury). 

The error is quite extensive and is in the slurm error file in this path: `/nesi/project/nesi02659/lra/users/jboe440/day3_assembly_qc/merqury/merqury2.37248577.err`

The script that was run is here: `/nesi/project/nesi02659/lra/users/jboe440/day3_assembly_qc/merqury/3.3-merqury_trio.sl`

`3.3-merqury_trio.sl` was modified to increase runtime due to failure to complete the first time, but did not run to completion and was killed by OOM.

@DininduSenanayake Can you take a look at it?

**Comment by DininduSenanayake** [comment]
This is resolved by changing the `util.sh` as per https://github.com/marbl/merqury/issues/82

Corresponding job ID for the successful run is as below and the output directory is `/nesi/project/nesi02659/lra/users/jboe440/day3_assembly_qc/merqury/dini-merqury-trio`. All .png files are there 

```
7293146       dini-merqury2   dinitrai+ Jul 02 15:32   01:06:52                         09:18:21    16           40G            COMPLETED  wmc024                         
37293146.batch batch                     Jul 02 15:32   01:06:52   09:18:20   09:18:20   09:18:21    16     1          35981156K COMPLETED  wmc024                         
37293146.exte+ extern                    Jul 02 15:32   01:06:52   00:00:00   00:00:00  00:00.001    16     1                  0 COMPLETED  wmc024     
```
