### ISSUE TITLE
change color of links maybe?

### ISSUE THREAD

**Issue by abueg** [GenomicsAotearoa/long-read-assembly#24]
https://github.com/GenomicsAotearoa/long-read-assembly/blob/fba215fa5d51321d18c57534a0ff69b10942abe5/docs/stylesheets/extra.css#L4C35-L4C35

Hi @DininduSenanayake ! I was wondering if it would be possible to change the color of hyperlinks in the text to stand out a little bit more? Sorry to be nitpicky, maybe my eyes are bad 😓 but I just missed a couple of the hyperlinks when reading through the text because the blue is dark enough to be close to the black, especially for shorter text (e.g., `Meryl` in the screenshot) 

<img width="1005" alt="image" src="https://github.com/GenomicsAotearoa/long-read-assembly/assets/48773001/b9b45cd2-865b-4855-8e4f-121928cf75c8">

No worries if not, though!

edit: oh, bolding the links could also work, but maybe having the color change just a bit brighter to stand out would be easier css-wise? not sure....

**Comment by DininduSenanayake** [comment]
Thanks for pointing this out and all done @abueg 

You are welcome to change it to another colour of your chose 

This is controlled by 
* Line 2 ` --md-typeset-a-color: #2596be;` on https://github.com/GenomicsAotearoa/long-read-assembly/blob/main/docs/stylesheets/extra.css
```
.md-content {
  --md-typeset-a-color: #2596be;
}
```
