### ISSUE TITLE
Embed additional supplementary PDFs

### ISSUE THREAD

**Issue by JSBoey** [GenomicsAotearoa/long-read-assembly#26]
There are additional files which are PDFs that need to be neatly embedded. Currently finding a method for it to work with Mkdocs.

**Comment by JSBoey** [comment]
Update: Additional materials in supplementary as links to PDFs. Still finding a way to embed.

**Comment by DininduSenanayake** [comment]
@JSBoey I am going to assign this to myself. Yeah there is something very strange about embedding PDFs but I did that for Imputation and RNA-seq. Took few rounds and different approaches in both cases

**Comment by JSBoey** [comment]
This is now complete as seen [here](https://genomicsaotearoa.github.io/long-read-assembly/supplementary/supplementary_4/)
